ALTER TABLE user_preferences
  ADD COLUMN IF NOT EXISTS reminder_time TIME NOT NULL DEFAULT '18:00',
  ADD COLUMN IF NOT EXISTS quiet_hours_start TIME NOT NULL DEFAULT '22:00',
  ADD COLUMN IF NOT EXISTS quiet_hours_end TIME NOT NULL DEFAULT '07:00';
