const fs = require('fs');
const assert = require('assert');
const server = fs.readFileSync('server.js', 'utf8');
const db = fs.readFileSync('db.js', 'utf8');
const migration = fs.readFileSync('migrations/001_initial_schema.sql', 'utf8');
const phaseTwoMigration = fs.readFileSync('migrations/002_sessions_and_job_runs.sql', 'utf8');
const phaseThreeMigration = fs.readFileSync('migrations/003_query_performance_indexes.sql', 'utf8');
const openapi = JSON.parse(fs.readFileSync('docs/openapi.json', 'utf8'));
const config = fs.readFileSync('config.js', 'utf8');
const errors = fs.readFileSync('middleware/errors.js', 'utf8');
const requestContext = fs.readFileSync('middleware/requestContext.js', 'utf8');
const csrf = fs.readFileSync('middleware/csrf.js', 'utf8');
const pagination = fs.readFileSync('middleware/pagination.js', 'utf8');
const jobs = fs.readFileSync('lib/jobRuns.js', 'utf8');
const streak = fs.readFileSync('routes/streak.js', 'utf8');
const quotes = fs.readFileSync('routes/quotes.js', 'utf8');
const announcements = fs.readFileSync('routes/announcements.js', 'utf8');
const packageJson = require('../package.json');

assert(server.includes("app.use('/api/messages', messageRoutes)"));
assert(server.includes("app.use('/api/announcements', announcementRoutes)"));
assert(server.includes("app.use('/api/quotes', quoteRoutes)"));
assert(server.includes("app.get('/health'"));
assert(server.includes("app.get('/health/live'"));
assert(server.includes("app.get('/health/ready'"));
assert(server.includes("app.get('/',"));
assert(server.includes('contentSecurityPolicy:'));
assert(!server.includes('contentSecurityPolicy: false'));
assert(server.includes("app.get('/api/openapi.json'"));
assert(server.indexOf('app.use(generalLimiter)') < server.indexOf("app.get('/health/live'"));
assert(db.includes("await pool.query('SELECT 1')"));
assert(migration.includes('CREATE TABLE IF NOT EXISTS announcements'));
assert(migration.includes('CREATE TABLE IF NOT EXISTS announcement_reads'));
assert(migration.includes('CREATE TABLE IF NOT EXISTS study_activity'));
assert(phaseTwoMigration.includes('CREATE TABLE IF NOT EXISTS user_sessions'));
assert(phaseTwoMigration.includes('CREATE TABLE IF NOT EXISTS job_runs'));
assert(phaseThreeMigration.includes('idx_messages_conversation_visible_created'));
assert(openapi.openapi === '3.0.3');
assert(openapi.paths['/api/auth/logout']);
assert(streak.includes("router.post('/activity'"));
assert(announcements.includes("router.get('/',"));
assert(announcements.includes("router.post('/:id/read',"));
assert(fs.readFileSync('routes/auth.js', 'utf8').includes("router.get('/me'"));
assert(quotes.includes("router.get('/daily'"));
assert(config.includes('Invalid environment configuration'));
assert(config.includes('configuredOrigins'));
assert(errors.includes('ROUTE_NOT_FOUND'));
assert(requestContext.includes('X-Request-Id'));
assert(server.includes('csrfProtection(config.corsOrigins)'));
assert(csrf.includes('CSRF_ORIGIN_REJECTED'));
assert(pagination.includes('totalPages'));
assert(jobs.includes('job_runs'));
assert(fs.readFileSync('routes/auth.js', 'utf8').includes("router.post('/logout'"));
assert(packageJson.dependencies.express === '^4.22.3');
assert(packageJson.dependencies['google-auth-library'] === '^11.1.0');
assert(packageJson.dependencies.helmet);
console.log('EduFlow backend contract smoke test: PASS');
